/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\WuWorkSpace\\code\\Blog\\wusp-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-45670e0d",
    path: "/passages/async function/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45670e0d").then(next)
    },
  },
  {
    path: "/passages/async function/index.html",
    redirect: "/passages/async function/"
  },
  {
    path: "/ES6/ES6%E7%9A%84%E9%87%8D%E9%9A%BE%E7%82%B9/async%E5%87%BD%E6%95%B0.html",
    redirect: "/passages/async function/"
  },
  {
    name: "v-7446e204",
    path: "/passages/Promise/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7446e204").then(next)
    },
  },
  {
    path: "/passages/Promise/index.html",
    redirect: "/passages/Promise/"
  },
  {
    path: "/ES6/ES6%E7%9A%84%E9%87%8D%E9%9A%BE%E7%82%B9/promise%E7%9A%84%E7%90%86%E8%A7%A3.html",
    redirect: "/passages/Promise/"
  },
  {
    name: "v-7b14fa39",
    path: "/passages/object-operation/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b14fa39").then(next)
    },
  },
  {
    path: "/passages/object-operation/index.html",
    redirect: "/passages/object-operation/"
  },
  {
    path: "/ES6/%E5%AF%B9%E8%B1%A1/2,%E5%AF%B9%E8%B1%A1%E7%9A%84%E6%93%8D%E4%BD%9C.html",
    redirect: "/passages/object-operation/"
  },
  {
    name: "v-2bef926d",
    path: "/passages/generator/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2bef926d").then(next)
    },
  },
  {
    path: "/passages/generator/index.html",
    redirect: "/passages/generator/"
  },
  {
    path: "/ES6/ES6%E7%9A%84%E9%87%8D%E9%9A%BE%E7%82%B9/generator%E5%87%BD%E6%95%B0.html",
    redirect: "/passages/generator/"
  },
  {
    name: "v-7e8a5381",
    path: "/passages/object-switch/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e8a5381").then(next)
    },
  },
  {
    path: "/passages/object-switch/index.html",
    redirect: "/passages/object-switch/"
  },
  {
    path: "/ES6/%E5%AF%B9%E8%B1%A1/3,%E5%AF%B9%E8%B1%A1%E7%9A%84%E8%BD%AC%E6%8D%A2.html",
    redirect: "/passages/object-switch/"
  },
  {
    name: "v-e6ab116e",
    path: "/passages/object-create/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e6ab116e").then(next)
    },
  },
  {
    path: "/passages/object-create/index.html",
    redirect: "/passages/object-create/"
  },
  {
    path: "/ES6/%E5%AF%B9%E8%B1%A1/1,%E5%AF%B9%E8%B1%A1%E7%9A%84%E5%88%9B%E5%BB%BA.html",
    redirect: "/passages/object-create/"
  },
  {
    name: "v-5c5f4960",
    path: "/passages/javascript-dataType/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c5f4960").then(next)
    },
  },
  {
    path: "/passages/javascript-dataType/index.html",
    redirect: "/passages/javascript-dataType/"
  },
  {
    path: "/ES6/%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B/0.js%E5%88%A4%E6%96%AD%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html",
    redirect: "/passages/javascript-dataType/"
  },
  {
    name: "v-167f7891",
    path: "/passages/function-create/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-167f7891").then(next)
    },
  },
  {
    path: "/passages/function-create/index.html",
    redirect: "/passages/function-create/"
  },
  {
    path: "/ES6/%E5%87%BD%E6%95%B0/1%EF%BC%8C%E5%87%BD%E6%95%B0%E7%9A%84%E5%A3%B0%E6%98%8E.html",
    redirect: "/passages/function-create/"
  },
  {
    name: "v-0793c4c2",
    path: "/passages/array-switch/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0793c4c2").then(next)
    },
  },
  {
    path: "/passages/array-switch/index.html",
    redirect: "/passages/array-switch/"
  },
  {
    path: "/ES6/%E6%95%B0%E7%BB%84/4,%E6%95%B0%E7%BB%84%E7%9A%84%E8%BD%AC%E6%8D%A2.html",
    redirect: "/passages/array-switch/"
  },
  {
    name: "v-d247372e",
    path: "/passages/array/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d247372e").then(next)
    },
  },
  {
    path: "/passages/array/index.html",
    redirect: "/passages/array/"
  },
  {
    path: "/ES6/%E6%95%B0%E7%BB%84/1,%E6%95%B0%E7%BB%84%E7%9A%84%E5%88%9B%E5%BB%BA.html",
    redirect: "/passages/array/"
  },
  {
    name: "v-543fc9da",
    path: "/passages/array-for/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-543fc9da").then(next)
    },
  },
  {
    path: "/passages/array-for/index.html",
    redirect: "/passages/array-for/"
  },
  {
    path: "/ES6/%E6%95%B0%E7%BB%84/2,%E6%95%B0%E7%BB%84%E7%9A%84%E5%BE%AA%E7%8E%AF.html",
    redirect: "/passages/array-for/"
  },
  {
    name: "v-0e7e7752",
    path: "/passages/array-operation/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e7e7752").then(next)
    },
  },
  {
    path: "/passages/array-operation/index.html",
    redirect: "/passages/array-operation/"
  },
  {
    path: "/ES6/%E6%95%B0%E7%BB%84/3,%E6%95%B0%E7%BB%84%E7%9A%84%E6%93%8D%E4%BD%9C.html",
    redirect: "/passages/array-operation/"
  },
  {
    name: "v-1d036ca0",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d036ca0").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-5ac5ad34",
    path: "/passages/ssh_key_create/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ac5ad34").then(next)
    },
  },
  {
    path: "/passages/ssh_key_create/index.html",
    redirect: "/passages/ssh_key_create/"
  },
  {
    path: "/Git%E5%AE%9E%E6%88%98%E6%89%8B%E5%86%8C/1,ssh%E7%A7%98%E9%92%A5%E7%94%9F%E6%88%90.html",
    redirect: "/passages/ssh_key_create/"
  },
  {
    name: "v-23296562",
    path: "/passages/React/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23296562").then(next)
    },
  },
  {
    path: "/passages/React/index.html",
    redirect: "/passages/React/"
  },
  {
    path: "/React/reactJs%E5%9F%BA%E7%A1%80/React.html",
    redirect: "/passages/React/"
  },
  {
    name: "v-4309a9b9",
    path: "/passages/git_tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4309a9b9").then(next)
    },
  },
  {
    path: "/passages/git_tag/index.html",
    redirect: "/passages/git_tag/"
  },
  {
    path: "/Git%E5%AE%9E%E6%88%98%E6%89%8B%E5%86%8C/3,git%E4%B8%ADtag%E7%9A%84%E4%BD%BF%E7%94%A8.html",
    redirect: "/passages/git_tag/"
  },
  {
    name: "v-f331410a",
    path: "/passages/git_steps/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f331410a").then(next)
    },
  },
  {
    path: "/passages/git_steps/index.html",
    redirect: "/passages/git_steps/"
  },
  {
    path: "/Git%E5%AE%9E%E6%88%98%E6%89%8B%E5%86%8C/2,git%E5%B8%B8%E7%94%A8%E6%93%8D%E4%BD%9C.html",
    redirect: "/passages/git_steps/"
  },
  {
    name: "v-2921a69c",
    path: "/passages/array-tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2921a69c").then(next)
    },
  },
  {
    path: "/passages/array-tools/index.html",
    redirect: "/passages/array-tools/"
  },
  {
    path: "/ES6/%E6%95%B0%E7%BB%84/5,%E6%95%B0%E7%BB%84%E7%9A%84%E5%B7%A5%E5%85%B7%E7%B1%BB.html",
    redirect: "/passages/array-tools/"
  },
  {
    name: "v-0ca1de26",
    path: "/passages/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ca1de26").then(next)
    },
  },
  {
    path: "/passages/npm/index.html",
    redirect: "/passages/npm/"
  },
  {
    path: "/nodeJS/%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/npm%E7%9B%B8%E5%85%B3.html",
    redirect: "/passages/npm/"
  },
  {
    name: "v-98ede362",
    path: "/passages/VUE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-98ede362").then(next)
    },
  },
  {
    path: "/passages/VUE/index.html",
    redirect: "/passages/VUE/"
  },
  {
    path: "/VUE/vue%E5%9F%BA%E7%A1%80/VUE.html",
    redirect: "/passages/VUE/"
  },
  {
    name: "v-6fe58743",
    path: "/passages/nginx/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6fe58743").then(next)
    },
  },
  {
    path: "/passages/nginx/index.html",
    redirect: "/passages/nginx/"
  },
  {
    path: "/%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9B%B8%E5%85%B3/nginx/nginx.html",
    redirect: "/passages/nginx/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]