/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\wushaopengCode\\博客\\wusp-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-aad5aab0",
    path: "/passages/async function/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aad5aab0").then(next)
    },
  },
  {
    path: "/passages/async function/index.html",
    redirect: "/passages/async function/"
  },
  {
    path: "/ES6/ES6%E7%9A%84%E9%87%8D%E9%9A%BE%E7%82%B9/async%E5%87%BD%E6%95%B0.html",
    redirect: "/passages/async function/"
  },
  {
    name: "v-769e37f0",
    path: "/passages/generator/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-769e37f0").then(next)
    },
  },
  {
    path: "/passages/generator/index.html",
    redirect: "/passages/generator/"
  },
  {
    path: "/ES6/ES6%E7%9A%84%E9%87%8D%E9%9A%BE%E7%82%B9/generator%E5%87%BD%E6%95%B0.html",
    redirect: "/passages/generator/"
  },
  {
    name: "v-cf255942",
    path: "/passages/Promise/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf255942").then(next)
    },
  },
  {
    path: "/passages/Promise/index.html",
    redirect: "/passages/Promise/"
  },
  {
    path: "/ES6/ES6%E7%9A%84%E9%87%8D%E9%9A%BE%E7%82%B9/promise%E7%9A%84%E7%90%86%E8%A7%A3.html",
    redirect: "/passages/Promise/"
  },
  {
    name: "v-145cfea4",
    path: "/passages/object-create/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-145cfea4").then(next)
    },
  },
  {
    path: "/passages/object-create/index.html",
    redirect: "/passages/object-create/"
  },
  {
    path: "/ES6/%E5%AF%B9%E8%B1%A1/1,%E5%AF%B9%E8%B1%A1%E7%9A%84%E5%88%9B%E5%BB%BA.html",
    redirect: "/passages/object-create/"
  },
  {
    name: "v-d1e31628",
    path: "/passages/function-create/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d1e31628").then(next)
    },
  },
  {
    path: "/passages/function-create/index.html",
    redirect: "/passages/function-create/"
  },
  {
    path: "/ES6/%E5%87%BD%E6%95%B0/1%EF%BC%8C%E5%87%BD%E6%95%B0%E7%9A%84%E5%A3%B0%E6%98%8E.html",
    redirect: "/passages/function-create/"
  },
  {
    name: "v-02c78194",
    path: "/passages/object-operation/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02c78194").then(next)
    },
  },
  {
    path: "/passages/object-operation/index.html",
    redirect: "/passages/object-operation/"
  },
  {
    path: "/ES6/%E5%AF%B9%E8%B1%A1/2,%E5%AF%B9%E8%B1%A1%E7%9A%84%E6%93%8D%E4%BD%9C.html",
    redirect: "/passages/object-operation/"
  },
  {
    name: "v-063cdadc",
    path: "/passages/object-switch/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-063cdadc").then(next)
    },
  },
  {
    path: "/passages/object-switch/index.html",
    redirect: "/passages/object-switch/"
  },
  {
    path: "/ES6/%E5%AF%B9%E8%B1%A1/3,%E5%AF%B9%E8%B1%A1%E7%9A%84%E8%BD%AC%E6%8D%A2.html",
    redirect: "/passages/object-switch/"
  },
  {
    name: "v-6da5682a",
    path: "/passages/javascript-dataType/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6da5682a").then(next)
    },
  },
  {
    path: "/passages/javascript-dataType/index.html",
    redirect: "/passages/javascript-dataType/"
  },
  {
    path: "/ES6/%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B/0.js%E5%88%A4%E6%96%AD%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html",
    redirect: "/passages/javascript-dataType/"
  },
  {
    name: "v-1e8eebc4",
    path: "/passages/array/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e8eebc4").then(next)
    },
  },
  {
    path: "/passages/array/index.html",
    redirect: "/passages/array/"
  },
  {
    path: "/ES6/%E6%95%B0%E7%BB%84/1,%E6%95%B0%E7%BB%84%E7%9A%84%E5%88%9B%E5%BB%BA.html",
    redirect: "/passages/array/"
  },
  {
    name: "v-481b5d96",
    path: "/passages/array-for/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-481b5d96").then(next)
    },
  },
  {
    path: "/passages/array-for/index.html",
    redirect: "/passages/array-for/"
  },
  {
    path: "/ES6/%E6%95%B0%E7%BB%84/2,%E6%95%B0%E7%BB%84%E7%9A%84%E5%BE%AA%E7%8E%AF.html",
    redirect: "/passages/array-for/"
  },
  {
    name: "v-ff19689c",
    path: "/passages/array-operation/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ff19689c").then(next)
    },
  },
  {
    path: "/passages/array-operation/index.html",
    redirect: "/passages/array-operation/"
  },
  {
    path: "/ES6/%E6%95%B0%E7%BB%84/3,%E6%95%B0%E7%BB%84%E7%9A%84%E6%93%8D%E4%BD%9C.html",
    redirect: "/passages/array-operation/"
  },
  {
    name: "v-7c3a0f92",
    path: "/passages/array-tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c3a0f92").then(next)
    },
  },
  {
    path: "/passages/array-tools/index.html",
    redirect: "/passages/array-tools/"
  },
  {
    path: "/ES6/%E6%95%B0%E7%BB%84/5,%E6%95%B0%E7%BB%84%E7%9A%84%E5%B7%A5%E5%85%B7%E7%B1%BB.html",
    redirect: "/passages/array-tools/"
  },
  {
    name: "v-f82eb60c",
    path: "/passages/array-switch/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f82eb60c").then(next)
    },
  },
  {
    path: "/passages/array-switch/index.html",
    redirect: "/passages/array-switch/"
  },
  {
    path: "/ES6/%E6%95%B0%E7%BB%84/4,%E6%95%B0%E7%BB%84%E7%9A%84%E8%BD%AC%E6%8D%A2.html",
    redirect: "/passages/array-switch/"
  },
  {
    name: "v-54a06b96",
    path: "/passages/git_steps/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54a06b96").then(next)
    },
  },
  {
    path: "/passages/git_steps/index.html",
    redirect: "/passages/git_steps/"
  },
  {
    path: "/Git%E5%AE%9E%E6%88%98%E6%89%8B%E5%86%8C/2,git%E5%B8%B8%E7%94%A8%E6%93%8D%E4%BD%9C.html",
    redirect: "/passages/git_steps/"
  },
  {
    name: "v-2191f594",
    path: "/passages/git_tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2191f594").then(next)
    },
  },
  {
    path: "/passages/git_tag/index.html",
    redirect: "/passages/git_tag/"
  },
  {
    path: "/Git%E5%AE%9E%E6%88%98%E6%89%8B%E5%86%8C/3,git%E4%B8%ADtag%E7%9A%84%E4%BD%BF%E7%94%A8.html",
    redirect: "/passages/git_tag/"
  },
  {
    name: "v-28feb94f",
    path: "/passages/ssh_key_create/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28feb94f").then(next)
    },
  },
  {
    path: "/passages/ssh_key_create/index.html",
    redirect: "/passages/ssh_key_create/"
  },
  {
    path: "/Git%E5%AE%9E%E6%88%98%E6%89%8B%E5%86%8C/1,ssh%E7%A7%98%E9%92%A5%E7%94%9F%E6%88%90.html",
    redirect: "/passages/ssh_key_create/"
  },
  {
    name: "v-2d8ced25",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d8ced25").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2b75e42e",
    path: "/passages/React/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b75e42e").then(next)
    },
  },
  {
    path: "/passages/React/index.html",
    redirect: "/passages/React/"
  },
  {
    path: "/React/React.html",
    redirect: "/passages/React/"
  },
  {
    name: "v-b7e7d72e",
    path: "/passages/VUE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b7e7d72e").then(next)
    },
  },
  {
    path: "/passages/VUE/index.html",
    redirect: "/passages/VUE/"
  },
  {
    path: "/VUE/VUE.html",
    redirect: "/passages/VUE/"
  },
  {
    name: "v-a8fc99f0",
    path: "/passages/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a8fc99f0").then(next)
    },
  },
  {
    path: "/passages/npm/index.html",
    redirect: "/passages/npm/"
  },
  {
    path: "/nodeJS/%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/npm%E7%9B%B8%E5%85%B3.html",
    redirect: "/passages/npm/"
  },
  {
    name: "v-2a851744",
    path: "/passages/nginx/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a851744").then(next)
    },
  },
  {
    path: "/passages/nginx/index.html",
    redirect: "/passages/nginx/"
  },
  {
    path: "/%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9B%B8%E5%85%B3/nginx/nginx.html",
    redirect: "/passages/nginx/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]