/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "async函数",
      "frontmatter": {
        "title": "async函数",
        "date": "2019-08-27",
        "permalink": "/passages/async function",
        "commentid": "async function"
      },
      "regularPath": "/ES6/ES6%E7%9A%84%E9%87%8D%E9%9A%BE%E7%82%B9/async%E5%87%BD%E6%95%B0.html",
      "relativePath": "ES6/ES6的重难点/async函数.md",
      "key": "v-aad5aab0",
      "path": "/passages/async function/",
      "headers": [
        {
          "level": 2,
          "title": "什么是 Async/Await？",
          "slug": "什么是-async-await？"
        },
        {
          "level": 2,
          "title": "使用async 处理异步任务",
          "slug": "使用async-处理异步任务"
        }
      ],
      "lastUpdated": "2019-12-4 19:30:24"
    },
    {
      "title": "generator函数",
      "frontmatter": {
        "title": "generator函数",
        "date": "2019-08-27",
        "permalink": "/passages/generator",
        "commentid": "generator"
      },
      "regularPath": "/ES6/ES6%E7%9A%84%E9%87%8D%E9%9A%BE%E7%82%B9/generator%E5%87%BD%E6%95%B0.html",
      "relativePath": "ES6/ES6的重难点/generator函数.md",
      "key": "v-769e37f0",
      "path": "/passages/generator/",
      "headers": [
        {
          "level": 2,
          "title": "generator是什么？",
          "slug": "generator是什么？"
        },
        {
          "level": 3,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 3,
          "title": "yield传参",
          "slug": "yield传参"
        },
        {
          "level": 3,
          "title": "yield返回",
          "slug": "yield返回"
        },
        {
          "level": 3,
          "title": "generator应用",
          "slug": "generator应用"
        }
      ],
      "lastUpdated": "2019-12-3 14:42:38"
    },
    {
      "title": "Promise",
      "frontmatter": {
        "title": "Promise",
        "date": "2019-08-27",
        "permalink": "/passages/Promise",
        "commentid": "Promise"
      },
      "regularPath": "/ES6/ES6%E7%9A%84%E9%87%8D%E9%9A%BE%E7%82%B9/promise%E7%9A%84%E7%90%86%E8%A7%A3.html",
      "relativePath": "ES6/ES6的重难点/promise的理解.md",
      "key": "v-cf255942",
      "path": "/passages/Promise/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "Promise的含义",
          "slug": "promise的含义"
        },
        {
          "level": 2,
          "title": "Promise的基本用法",
          "slug": "promise的基本用法"
        },
        {
          "level": 3,
          "title": ".then()",
          "slug": "then"
        },
        {
          "level": 3,
          "title": ".all()",
          "slug": "all"
        },
        {
          "level": 3,
          "title": "特点一:Promise 新建后就会立即执行",
          "slug": "特点一-promise-新建后就会立即执行"
        },
        {
          "level": 2,
          "title": "案例",
          "slug": "案例"
        }
      ],
      "lastUpdated": "2019-12-3 10:21:22"
    },
    {
      "title": "对象的创建",
      "frontmatter": {
        "title": "对象的创建",
        "date": "2019-08-15",
        "permalink": "/passages/object-create",
        "commentid": "object-create"
      },
      "regularPath": "/ES6/%E5%AF%B9%E8%B1%A1/1,%E5%AF%B9%E8%B1%A1%E7%9A%84%E5%88%9B%E5%BB%BA.html",
      "relativePath": "ES6/对象/1,对象的创建.md",
      "key": "v-145cfea4",
      "path": "/passages/object-create/",
      "headers": [
        {
          "level": 2,
          "title": "创建对象Object.create(obj)",
          "slug": "创建对象object-create-obj"
        },
        {
          "level": 2,
          "title": "Object.create实现类式继承",
          "slug": "object-create实现类式继承"
        },
        {
          "level": 2,
          "title": "复制对象",
          "slug": "复制对象"
        },
        {
          "level": 3,
          "title": "方法一，JSON字符化",
          "slug": "方法一，json字符化"
        },
        {
          "level": 3,
          "title": "方法二，Object.assign()",
          "slug": "方法二，object-assign"
        }
      ],
      "lastUpdated": "2019-8-23 19:23:35"
    },
    {
      "title": "函数的声明",
      "frontmatter": {
        "title": "函数的声明",
        "date": "2019-08-15",
        "permalink": "/passages/function-create",
        "commentid": "function-create"
      },
      "regularPath": "/ES6/%E5%87%BD%E6%95%B0/1%EF%BC%8C%E5%87%BD%E6%95%B0%E7%9A%84%E5%A3%B0%E6%98%8E.html",
      "relativePath": "ES6/函数/1，函数的声明.md",
      "key": "v-d1e31628",
      "path": "/passages/function-create/",
      "headers": [
        {
          "level": 2,
          "title": "1，函数式声明",
          "slug": "_1，函数式声明"
        },
        {
          "level": 2,
          "title": "2,函数表达式声明",
          "slug": "_2-函数表达式声明"
        },
        {
          "level": 2,
          "title": "3,条件中的函数声明",
          "slug": "_3-条件中的函数声明"
        },
        {
          "level": 2,
          "title": "4,匿名函数",
          "slug": "_4-匿名函数"
        }
      ],
      "lastUpdated": "2019-8-23 19:23:35"
    },
    {
      "title": "对象的操作",
      "frontmatter": {
        "title": "对象的操作",
        "date": "2019-08-15",
        "permalink": "/passages/object-operation",
        "commentid": "object-operation"
      },
      "regularPath": "/ES6/%E5%AF%B9%E8%B1%A1/2,%E5%AF%B9%E8%B1%A1%E7%9A%84%E6%93%8D%E4%BD%9C.html",
      "relativePath": "ES6/对象/2,对象的操作.md",
      "key": "v-02c78194",
      "path": "/passages/object-operation/",
      "headers": [
        {
          "level": 2,
          "title": "循环对象",
          "slug": "循环对象"
        },
        {
          "level": 2,
          "title": "向对象中增加属性",
          "slug": "向对象中增加属性"
        },
        {
          "level": 2,
          "title": "删除对象的属性",
          "slug": "删除对象的属性"
        }
      ],
      "lastUpdated": "2019-8-23 19:23:35"
    },
    {
      "title": "对象的转换",
      "frontmatter": {
        "title": "对象的转换",
        "date": "2019-08-15",
        "permalink": "/passages/object-switch",
        "commentid": "object-switch"
      },
      "regularPath": "/ES6/%E5%AF%B9%E8%B1%A1/3,%E5%AF%B9%E8%B1%A1%E7%9A%84%E8%BD%AC%E6%8D%A2.html",
      "relativePath": "ES6/对象/3,对象的转换.md",
      "key": "v-063cdadc",
      "path": "/passages/object-switch/",
      "headers": [
        {
          "level": 2,
          "title": "对象转数组",
          "slug": "对象转数组"
        },
        {
          "level": 2,
          "title": "数组转对象",
          "slug": "数组转对象"
        },
        {
          "level": 2,
          "title": "JSON转换",
          "slug": "json转换"
        }
      ],
      "lastUpdated": "2019-8-23 19:23:35"
    },
    {
      "title": "js判断数据类型",
      "frontmatter": {
        "title": "js判断数据类型",
        "date": "2019-08-13",
        "permalink": "/passages/javascript-dataType",
        "commentid": "javascript-dataType"
      },
      "regularPath": "/ES6/%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B/0.js%E5%88%A4%E6%96%AD%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html",
      "relativePath": "ES6/数据类型/0.js判断数据类型.md",
      "key": "v-6da5682a",
      "path": "/passages/javascript-dataType/",
      "headers": [
        {
          "level": 2,
          "title": "一，js中的类型",
          "slug": "一，js中的类型"
        },
        {
          "level": 2,
          "title": "二、判断数据类型",
          "slug": "二、判断数据类型"
        },
        {
          "level": 3,
          "title": "终结封装版本",
          "slug": "终结封装版本"
        },
        {
          "level": 3,
          "title": "1.使用typeof",
          "slug": "_1-使用typeof"
        },
        {
          "level": 3,
          "title": "2.使用instanceof",
          "slug": "_2-使用instanceof"
        },
        {
          "level": 3,
          "title": "3.使用constructor",
          "slug": "_3-使用constructor"
        },
        {
          "level": 3,
          "title": "3.使用Object.prototype.toString.call",
          "slug": "_3-使用object-prototype-tostring-call"
        }
      ],
      "lastUpdated": "2019-8-15 18:13:36"
    },
    {
      "title": "数组的创建",
      "frontmatter": {
        "title": "数组的创建",
        "date": "2019-08-13",
        "permalink": "/passages/array",
        "commentid": "array"
      },
      "regularPath": "/ES6/%E6%95%B0%E7%BB%84/1,%E6%95%B0%E7%BB%84%E7%9A%84%E5%88%9B%E5%BB%BA.html",
      "relativePath": "ES6/数组/1,数组的创建.md",
      "key": "v-1e8eebc4",
      "path": "/passages/array/",
      "headers": [
        {
          "level": 2,
          "title": "复制(克隆)数组",
          "slug": "复制-克隆-数组"
        },
        {
          "level": 2,
          "title": "创建数组",
          "slug": "创建数组"
        }
      ],
      "lastUpdated": "2020-6-4 09:47:29"
    },
    {
      "title": "数组的循环",
      "frontmatter": {
        "title": "数组的循环",
        "date": "2019-08-13",
        "permalink": "/passages/array-for",
        "commentid": "array-for"
      },
      "regularPath": "/ES6/%E6%95%B0%E7%BB%84/2,%E6%95%B0%E7%BB%84%E7%9A%84%E5%BE%AA%E7%8E%AF.html",
      "relativePath": "ES6/数组/2,数组的循环.md",
      "key": "v-481b5d96",
      "path": "/passages/array-for/",
      "headers": [
        {
          "level": 2,
          "title": "map()",
          "slug": "map"
        },
        {
          "level": 2,
          "title": "reduce()",
          "slug": "reduce"
        },
        {
          "level": 2,
          "title": "foreach()",
          "slug": "foreach"
        },
        {
          "level": 2,
          "title": "filter()",
          "slug": "filter"
        },
        {
          "level": 2,
          "title": "every()",
          "slug": "every"
        },
        {
          "level": 2,
          "title": "some()",
          "slug": "some"
        },
        {
          "level": 2,
          "title": "find()",
          "slug": "find"
        }
      ],
      "lastUpdated": "2019-12-2 14:03:52"
    },
    {
      "title": "数组的操作",
      "frontmatter": {
        "title": "数组的操作",
        "date": "2019-08-14",
        "permalink": "/passages/array-operation",
        "commentid": "array-operation"
      },
      "regularPath": "/ES6/%E6%95%B0%E7%BB%84/3,%E6%95%B0%E7%BB%84%E7%9A%84%E6%93%8D%E4%BD%9C.html",
      "relativePath": "ES6/数组/3,数组的操作.md",
      "key": "v-ff19689c",
      "path": "/passages/array-operation/",
      "headers": [
        {
          "level": 2,
          "title": "合并多个数组",
          "slug": "合并多个数组"
        },
        {
          "level": 3,
          "title": "concat()",
          "slug": "concat"
        },
        {
          "level": 2,
          "title": "删除数组元素",
          "slug": "删除数组元素"
        },
        {
          "level": 3,
          "title": "splice()",
          "slug": "splice"
        },
        {
          "level": 2,
          "title": "增加元素到数组",
          "slug": "增加元素到数组"
        },
        {
          "level": 3,
          "title": "push()",
          "slug": "push"
        },
        {
          "level": 3,
          "title": "unshift()",
          "slug": "unshift"
        },
        {
          "level": 3,
          "title": "splice()",
          "slug": "splice-2"
        },
        {
          "level": 2,
          "title": "从数组中选择元素",
          "slug": "从数组中选择元素"
        },
        {
          "level": 3,
          "title": "slice()",
          "slug": "slice"
        },
        {
          "level": 3,
          "title": "find()",
          "slug": "find"
        }
      ],
      "lastUpdated": "2020-6-4 09:47:29"
    },
    {
      "title": "数组的工具类",
      "frontmatter": {
        "title": "数组的工具类",
        "date": "2019-08-14",
        "permalink": "/passages/array-tools",
        "commentid": "array-tools"
      },
      "regularPath": "/ES6/%E6%95%B0%E7%BB%84/5,%E6%95%B0%E7%BB%84%E7%9A%84%E5%B7%A5%E5%85%B7%E7%B1%BB.html",
      "relativePath": "ES6/数组/5,数组的工具类.md",
      "key": "v-7c3a0f92",
      "path": "/passages/array-tools/",
      "headers": [
        {
          "level": 2,
          "title": "1.1 检测是否为数组",
          "slug": "_1-1-检测是否为数组"
        },
        {
          "level": 2,
          "title": "1.2 数组去重",
          "slug": "_1-2-数组去重"
        },
        {
          "level": 3,
          "title": "终结版本",
          "slug": "终结版本"
        },
        {
          "level": 3,
          "title": "set简单去重",
          "slug": "set简单去重"
        },
        {
          "level": 3,
          "title": "set对象去重",
          "slug": "set对象去重"
        },
        {
          "level": 3,
          "title": "map 对象属性去重",
          "slug": "map-对象属性去重"
        },
        {
          "level": 2,
          "title": "1.3数组排序",
          "slug": "_1-3数组排序"
        },
        {
          "level": 3,
          "title": "sort()",
          "slug": "sort"
        },
        {
          "level": 3,
          "title": "简单排序",
          "slug": "简单排序"
        },
        {
          "level": 3,
          "title": "数字排序",
          "slug": "数字排序"
        },
        {
          "level": 3,
          "title": "对象属性（数字）排序",
          "slug": "对象属性（数字）排序"
        },
        {
          "level": 3,
          "title": "对象属性（字符）排序",
          "slug": "对象属性（字符）排序"
        },
        {
          "level": 2,
          "title": "1.4 特殊数组处理",
          "slug": "_1-4-特殊数组处理"
        },
        {
          "level": 3,
          "title": "table对象对比",
          "slug": "table对象对比"
        }
      ],
      "lastUpdated": "2019-8-15 18:13:36"
    },
    {
      "title": "数组的转换",
      "frontmatter": {
        "title": "数组的转换",
        "date": "2019-08-13",
        "permalink": "/passages/array-switch",
        "commentid": "array-switch"
      },
      "regularPath": "/ES6/%E6%95%B0%E7%BB%84/4,%E6%95%B0%E7%BB%84%E7%9A%84%E8%BD%AC%E6%8D%A2.html",
      "relativePath": "ES6/数组/4,数组的转换.md",
      "key": "v-f82eb60c",
      "path": "/passages/array-switch/",
      "headers": [
        {
          "level": 2,
          "title": "数组转字符串",
          "slug": "数组转字符串"
        },
        {
          "level": 2,
          "title": "字符串转数组",
          "slug": "字符串转数组"
        },
        {
          "level": 2,
          "title": "对象转化为数组",
          "slug": "对象转化为数组"
        },
        {
          "level": 3,
          "title": "Object.keys()",
          "slug": "object-keys"
        }
      ],
      "lastUpdated": "2019-8-15 18:13:36"
    },
    {
      "title": "git常用操作",
      "frontmatter": {
        "title": "git常用操作",
        "date": "2019-08-12",
        "permalink": "/passages/git_steps",
        "commentid": "git_steps"
      },
      "regularPath": "/Git%E5%AE%9E%E6%88%98%E6%89%8B%E5%86%8C/2,git%E5%B8%B8%E7%94%A8%E6%93%8D%E4%BD%9C.html",
      "relativePath": "Git实战手册/2,git常用操作.md",
      "key": "v-54a06b96",
      "path": "/passages/git_steps/",
      "headers": [
        {
          "level": 2,
          "title": "Git回滚到某个commit",
          "slug": "git回滚到某个commit"
        },
        {
          "level": 2,
          "title": "拉取远程分支到本地",
          "slug": "拉取远程分支到本地"
        },
        {
          "level": 2,
          "title": "git本地文件夹的删除和添加",
          "slug": "git本地文件夹的删除和添加"
        },
        {
          "level": 2,
          "title": "git删除远程仓库的文件",
          "slug": "git删除远程仓库的文件"
        },
        {
          "level": 2,
          "title": "branch基本操作",
          "slug": "branch基本操作"
        }
      ],
      "lastUpdated": "2019-8-23 19:23:35"
    },
    {
      "title": "git中tag的使用",
      "frontmatter": {
        "title": "git中tag的使用",
        "date": "2019-08-12",
        "permalink": "/passages/git_tag",
        "commentid": "git_tag"
      },
      "regularPath": "/Git%E5%AE%9E%E6%88%98%E6%89%8B%E5%86%8C/3,git%E4%B8%ADtag%E7%9A%84%E4%BD%BF%E7%94%A8.html",
      "relativePath": "Git实战手册/3,git中tag的使用.md",
      "key": "v-2191f594",
      "path": "/passages/git_tag/",
      "headers": [
        {
          "level": 2,
          "title": "tag标签的常用操作",
          "slug": "tag标签的常用操作"
        },
        {
          "level": 2,
          "title": "操作标签",
          "slug": "操作标签"
        },
        {
          "level": 2,
          "title": "根据tag回退版本修改bug",
          "slug": "根据tag回退版本修改bug"
        }
      ],
      "lastUpdated": "2019-8-23 19:23:35"
    },
    {
      "title": "ssh秘钥的生成",
      "frontmatter": {
        "title": "ssh秘钥的生成",
        "date": "2019-08-09",
        "permalink": "/passages/ssh_key_create",
        "commentid": "ssh_key_create"
      },
      "regularPath": "/Git%E5%AE%9E%E6%88%98%E6%89%8B%E5%86%8C/1,ssh%E7%A7%98%E9%92%A5%E7%94%9F%E6%88%90.html",
      "relativePath": "Git实战手册/1,ssh秘钥生成.md",
      "key": "v-28feb94f",
      "path": "/passages/ssh_key_create/",
      "headers": [
        {
          "level": 2,
          "title": "1.检查是否存在SSH秘钥",
          "slug": "_1-检查是否存在ssh秘钥"
        },
        {
          "level": 2,
          "title": "2.运行命令生成SSH秘钥",
          "slug": "_2-运行命令生成ssh秘钥"
        },
        {
          "level": 2,
          "title": "linux信任秘钥的修改",
          "slug": "linux信任秘钥的修改"
        }
      ],
      "lastUpdated": "2019-8-27 19:59:40"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "./flower.jpg",
        "heroText": "一腔诗意",
        "tagline": "种一棵树最好的时间是十年前，其次就是现在。",
        "actionText": "进入导航 →",
        "actionLink": "/passages/javascript-datatype/",
        "footer": "MIT Licensed | Copyright © 2019 一腔诗意"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2d8ced25",
      "path": "/",
      "lastUpdated": "2019-12-3 10:20:41"
    },
    {
      "title": "React相关",
      "frontmatter": {
        "title": "React相关",
        "date": "2020-06-04",
        "permalink": "/passages/React",
        "commentid": "React"
      },
      "regularPath": "/React/React.html",
      "relativePath": "React/React.md",
      "key": "v-2b75e42e",
      "path": "/passages/React/",
      "lastUpdated": "2020-6-4 10:21:44"
    },
    {
      "title": "VUE相关",
      "frontmatter": {
        "title": "VUE相关",
        "date": "2020-06-04",
        "permalink": "/passages/VUE",
        "commentid": "VUE"
      },
      "regularPath": "/VUE/VUE.html",
      "relativePath": "VUE/VUE.md",
      "key": "v-b7e7d72e",
      "path": "/passages/VUE/",
      "headers": [
        {
          "level": 2,
          "title": "VUE的精髓——组件",
          "slug": "vue的精髓-组件"
        },
        {
          "level": 2,
          "title": "组件的分类",
          "slug": "组件的分类"
        }
      ],
      "lastUpdated": "2020-6-4 10:21:44"
    },
    {
      "title": "npm相关",
      "frontmatter": {
        "title": "npm相关",
        "date": "2019-12-04",
        "permalink": "/passages/npm",
        "commentid": "npm"
      },
      "regularPath": "/nodeJS/%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86/npm%E7%9B%B8%E5%85%B3.html",
      "relativePath": "nodeJS/基础知识/npm相关.md",
      "key": "v-a8fc99f0",
      "path": "/passages/npm/",
      "headers": [
        {
          "level": 2,
          "title": "npm install",
          "slug": "npm-install"
        },
        {
          "level": 2,
          "title": "环境变量（NODE_ENV）设置",
          "slug": "环境变量（node-env）设置"
        },
        {
          "level": 3,
          "title": "常规使用",
          "slug": "常规使用"
        },
        {
          "level": 3,
          "title": "特殊场景：",
          "slug": "特殊场景："
        }
      ],
      "lastUpdated": "2020-6-4 10:01:00"
    },
    {
      "title": "nginx",
      "frontmatter": {
        "title": "nginx",
        "date": "2019-09-02",
        "permalink": "/passages/nginx",
        "commentid": "nginx"
      },
      "regularPath": "/%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9B%B8%E5%85%B3/nginx/nginx.html",
      "relativePath": "服务器相关/nginx/nginx.md",
      "key": "v-2a851744",
      "path": "/passages/nginx/",
      "headers": [
        {
          "level": 2,
          "title": "nginx操作",
          "slug": "nginx操作"
        },
        {
          "level": 3,
          "title": "定位nginx",
          "slug": "定位nginx"
        },
        {
          "level": 3,
          "title": "nginx命令",
          "slug": "nginx命令"
        },
        {
          "level": 2,
          "title": "linux 下常用命令",
          "slug": "linux-下常用命令"
        },
        {
          "level": 3,
          "title": "操作文件夹",
          "slug": "操作文件夹"
        },
        {
          "level": 3,
          "title": "操作文件",
          "slug": "操作文件"
        }
      ],
      "lastUpdated": "2019-12-2 14:03:52"
    }
  ],
  "themeConfig": {
    "repo": "wusp1994/wusp-blog",
    "navbar": true,
    "editLinks": true,
    "editLinkText": "在 GitHub 上编辑此页",
    "lastUpdated": "更新于",
    "sidebar": {
      "/Git实战手册/": [
        {
          "title": "Git实战手册",
          "children": [
            "1,ssh秘钥生成",
            "2,git常用操作",
            "3,git中tag的使用"
          ],
          "collapsable": true,
          "sidebarDepth": 3
        }
      ],
      "/ES6/": [
        {
          "title": "数据类型",
          "children": [
            "数据类型/0.js判断数据类型"
          ],
          "collapsable": true,
          "sidebarDepth": 3
        },
        {
          "title": "数组",
          "children": [
            "数组/1,数组的创建",
            "数组/2,数组的循环",
            "数组/3,数组的操作",
            "数组/4,数组的转换",
            "数组/5,数组的工具类"
          ],
          "collapsable": true,
          "sidebarDepth": 3
        },
        {
          "title": "对象",
          "children": [
            "对象/1,对象的创建",
            "对象/2,对象的操作",
            "对象/3,对象的转换"
          ],
          "collapsable": true,
          "sidebarDepth": 3
        },
        {
          "title": "函数",
          "children": [
            "函数/1，函数的声明"
          ],
          "collapsable": true,
          "sidebarDepth": 3
        },
        {
          "title": "ES6的重难点",
          "children": [
            "ES6的重难点/async函数",
            "ES6的重难点/generator函数",
            "ES6的重难点/promise的理解"
          ],
          "collapsable": true,
          "sidebarDepth": 3
        }
      ],
      "/服务器相关/": [
        {
          "title": "nginx",
          "children": [
            "nginx/nginx"
          ],
          "collapsable": true,
          "sidebarDepth": 3
        }
      ],
      "/nodeJS/": [
        {
          "title": "基础知识",
          "children": [
            "基础知识/npm相关"
          ],
          "collapsable": true,
          "sidebarDepth": 3
        }
      ],
      "/VUE/": [
        {
          "title": "VUE",
          "children": [
            "VUE/VUE"
          ],
          "collapsable": true,
          "sidebarDepth": 3
        }
      ],
      "/React/": [
        {
          "title": "React",
          "children": [
            "React/React"
          ],
          "collapsable": true,
          "sidebarDepth": 3
        }
      ]
    },
    "nav": [
      {
        "text": "核心技术",
        "items": [
          {
            "text": "js基础",
            "items": [
              {
                "text": "javascript",
                "link": "/passages/javascript-datatype/"
              },
              {
                "text": "VUE",
                "link": "/passages/VUE/"
              },
              {
                "text": "React",
                "link": "/passages/React/"
              },
              {
                "text": "angular",
                "link": ""
              }
            ]
          },
          {
            "text": "CSS3",
            "items": [
              {
                "text": "布局",
                "link": ""
              },
              {
                "text": "CSS3D",
                "link": ""
              },
              {
                "text": "高性能渲染",
                "link": ""
              }
            ]
          }
        ]
      },
      {
        "text": "Node.js",
        "items": [
          {
            "items": [
              {
                "text": "核心知识",
                "link": "/passages/npm/"
              },
              {
                "text": "express",
                "link": ""
              },
              {
                "text": "核心API",
                "link": ""
              },
              {
                "text": "koa",
                "link": ""
              },
              {
                "text": "Egg",
                "link": ""
              },
              {
                "text": "微服务",
                "link": ""
              }
            ]
          }
        ]
      },
      {
        "text": "Typescript",
        "items": [
          {
            "items": [
              {
                "text": "Typescript",
                "link": ""
              }
            ]
          }
        ]
      },
      {
        "text": "工程开发",
        "items": [
          {
            "text": "版本管理",
            "items": [
              {
                "text": "git",
                "link": "/passages/ssh_key_create/"
              }
            ]
          },
          {
            "text": "构建工具",
            "items": [
              {
                "text": "Webpack",
                "link": ""
              },
              {
                "text": "Grunt",
                "link": ""
              },
              {
                "text": "Gulp",
                "link": ""
              }
            ]
          },
          {
            "text": "自动化测试",
            "items": [
              {
                "text": "karma",
                "link": ""
              },
              {
                "text": "mocha",
                "link": ""
              },
              {
                "text": "Jest",
                "link": ""
              }
            ]
          }
        ]
      },
      {
        "text": "编程思想",
        "items": [
          {
            "text": "编程范式",
            "items": [
              {
                "text": "面向对象编程",
                "link": ""
              },
              {
                "text": "函数式编程",
                "link": ""
              },
              {
                "text": "响应式编程",
                "link": ""
              },
              {
                "text": "面向切面编程",
                "link": ""
              }
            ]
          },
          {
            "text": "设计模式",
            "items": [
              {
                "text": "1，单例模式",
                "link": ""
              },
              {
                "text": "2，代理模式",
                "link": ""
              },
              {
                "text": "3，命令模式",
                "link": ""
              },
              {
                "text": "4，订阅发布模式",
                "link": ""
              },
              {
                "text": "5，职责链模式",
                "link": ""
              }
            ]
          },
          {
            "text": "设计法则",
            "items": [
              {
                "text": "1，单一职责原则",
                "link": ""
              },
              {
                "text": "2，开放封闭原则",
                "link": ""
              },
              {
                "text": "3，李氏替换原则",
                "link": ""
              },
              {
                "text": "4，接口独立原则",
                "link": ""
              },
              {
                "text": "5，依赖倒置原则",
                "link": ""
              }
            ]
          }
        ]
      },
      {
        "text": "服务器相关",
        "items": [
          {
            "items": [
              {
                "text": "nginx",
                "link": "/passages/nginx/"
              },
              {
                "text": "tomcat",
                "link": "/passages/nginx/"
              }
            ]
          }
        ]
      }
    ],
    "displayAllHeaders": false
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": " 一腔诗意",
      "description": "种一棵树最好的时间是十年前，其次就是现在。",
      "path": "/"
    },
    "/en/": {
      "lang": "en-US",
      "title": "wuSp's Blog",
      "description": "The best time to plant a tree is ten years ago, followed by now.",
      "path": "/en/"
    }
  }
}